live_config_reload = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x000000"
foreground = "0xc0caf5"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 9

[font.bold]
family = "MesloLGL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
